include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    
    # Naming
    constant_identifier_names: true
    file_names: true
    package_names: true
    
    # Documentation
    public_member_api_docs: false
    
    # Imports
    avoid_relative_lib_imports: true
    directives_ordering: true
    
    # Types
    always_specify_types: false
    avoid_dynamic_calls: false
    
    # Performance
    avoid_slow_async_io: true
    
    # Flutter specific
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
